apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  labels:
    app: crawler
spec:
  type: NodePort
  selector:
    app: crawler
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080